name: Build with opam

on:
  push:
    branches: [ partial_eval ]
    paths: [ '*.opam', '.github/**' ]
  pull_request:
    paths: [ '*.opam', '.github/**' ]
  workflow_dispatch:

# only run one instance of this action at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.09
    - run: opam install dune
    - run: opam install . --deps-only --with-test
    - run: opam exec -- dune build --profile release

